# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    dir: "./"
    deps: [docker-up]
    cmds:
      - tygo generate
      - task web & task rest

  rest:
    dir: "./"
    cmds:
      - mkdir -p .out
      - air -c rest.air.toml

  web:
    dir: "./web/"
    cmds:
      - npm run dev

  docker-up:
    dir: "./"
    cmds:
      - ./.dev/create-certs.sh
      - docker compose up -d --wait

  reset:
    dir: "./"
    cmds:
      - docker compose down -v
      - task: docker-up