/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserType = "client" | "tenant";

export interface Permission {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  key: string;
  roleId: string;
}

export interface Role {
  createdAt: Generated<Timestamp>;
  default: boolean;
  id: Generated<string>;
  name: string;
  tenantId: string;
  type: UserType;
}

export interface Tenant {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  roleId: string;
  tenantId: string;
  type: UserType;
}

export interface DB {
  permission: Permission;
  role: Role;
  tenant: Tenant;
  user: User;
}
