/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type TaskStatus = "complete" | "failed" | "pending" | "running";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserType = "client" | "tenant";

export interface Permission {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  key: string;
  roleId: string;
}

export interface Role {
  createdAt: Generated<Timestamp>;
  default: boolean;
  id: Generated<string>;
  name: string;
  tenantId: string;
  type: UserType;
}

export interface Task {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  data: Json;
  id: Generated<string>;
  lastError: string | null;
  lastRun: Timestamp | null;
  maxAttempts: Generated<number>;
  status: Generated<TaskStatus>;
  tag: string;
  tenantId: string | null;
  workerId: string | null;
}

export interface Tenant {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  roleId: string;
  tenantId: string;
  type: UserType;
}

export interface UserCredential {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  passwordHash: string | null;
  totpSecret: string | null;
  userId: string;
}

export interface DB {
  permission: Permission;
  role: Role;
  task: Task;
  tenant: Tenant;
  user: User;
  userCredential: UserCredential;
}
