services:
  db:
    image: postgres:18
    restart: no
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coli
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: >
        bash -c "pg_isready -U postgres -d coli && pg_isready -U postgres -d iam"
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 2s

  traefik:
    image: traefik:v3.6
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    environment:
      - GIN_MODE=release
    volumes:
      - ./casdoor/conf:/conf
      - ./casdoor/logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
