# routes.yml
http:
  routers:

    fe-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "fe-service"
      priority: 10

    rest-router:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "rest-service"
      priority: 20

  services:
    fe-service:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:6565"
    rest-service:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:6464"

tls:
  certificates:
    - certFile: /etc/traefik/cert.pem
      keyFile: /etc/traefik/key.pem
