# routes.yml
http:
  routers:
    fe-router:
      rule: "Host(`coli.localhost`) && PathPrefix(`/`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "fe-service"
      priority: 1

    rest-router:
      rule: "Host(`coli.localhost`) && PathPrefix(`/api`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "rest-service"
      priority: 100

  services:
    fe-service:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:6565"
    rest-service:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:6464"

tls:
  certificates:
    - certFile: /etc/traefik/cert.pem
      keyFile: /etc/traefik/key.pem
